.TH TESTENV 1
.SH NAME
testenv \- runs TestEnv HydraTK extension
.SH SYNOPSIS
.B testenv
[\fBoptions\fR]
.B command
.SH DESCRIPTION
\fBTestEnv\fR extension provides testing environment for learning automated testing together with Yoda extension.

TestEnv provides simple CRM application with following interfaces:
  \fBDB\fR - interface to SQLite database
  \fBREST\fR - interface to REST services on web server
  \fBSOAP\fR - interface to SOAP services on web server
.SH COMMANDS
\fBhelp\fR - prints help

\fBinstall\fR - install testing environment database

\fBrun\fR - start testing environment
.SH GLOBAL OPTIONS
\fB-c, --config <file>\fR - reads the alternate configuration file

\fB-d, --debug <level>\fR - debug turned on with specified level > 0

\fB-e, --debug-channel <channel number, ..>\fR - debug channel filter turned on

\fB-f, --force\fR - enforces command

\fB-h, --home\fR - sets htk_root_dir to the current user home directory

\fB-i, --interactive\fR - turns on interactive mode

\fB-l, --language <language>\fR - sets the text output language, the list of available languages is specified in the docs

\fB-m, --run-mode <mode>\fR - sets the running mode, the list of available modes is specified in the docs
.SH FILES AND DIRECTORIES
Configuration file: /etc/hydratk/conf.d/hydratk-ext-testenv.conf

Extension directory: /var/local/hydratk/testenv

.SH AUTHOR
Petr Rašek (bowman@hydratk.org), HydraTK Team (team@hydratk.org)
.SH INTERNET RESOURCES
Main website: https://www.extensions.hydratk.org/testenv

Documentation: https://www.hydratk.org/docs

Downloads https://pypi.python.org/pypi/hydratk-ext-testenv, https://github.com/hydratk/hydratk-ext-testenv
.SH LICENSING
hydratk-ext-testenv is distributed under BSD license. See the file "LICENSE.txt" in the source distribution for information.